name: Postman-Newman-GHActions
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm i
    - name: Run Newman Tests
      run: npm run newman-run
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: report
        path: newman/
        retention-days: 30
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
          PERSONAL_TOKEN:  ${{ secrets.TOKEN123 }}
          PUBLISH_BRANCH: gh-pages



    
