name: Newman Tests

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  newman:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Replace with your desired Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Run Newman tests
      run: npx newman run <path_to_your_collection_file>  # Replace with the path to your collection file




    
